language: java

jdk:
  - oraclejdk8
  
branches:
  only:
    - master
    - development
    
notifications:
  email:
    recipients:
      - fclopezjurado@gmail.com
      
script: mvn test